---
manager:
  hosts:
    SPM:
      ansible_host: 10.10.10.170
search:
  hosts:
    SPS:
      ansible_host: 10.10.10.171
indexers:
  hosts:
    SPI01:
      ansible_host: 10.10.10.172
    SPI02:
      ansible_host: 10.10.10.173
    SPI03:
      ansible_host: 10.10.10.174
